// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbNBrD-_WzemfLa087b7r0zJ49CIZsM08',
    appId: '1:26510599933:web:9398169f345ce3aaad0094',
    messagingSenderId: '26510599933',
    projectId: 'cmsc23-c5l-ajhao',
    authDomain: 'cmsc23-c5l-ajhao.firebaseapp.com',
    storageBucket: 'cmsc23-c5l-ajhao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6HGLJ1ECFDPLTeTW419AaJfzPG8YhZXo',
    appId: '1:26510599933:android:26cc1c60220f3b85ad0094',
    messagingSenderId: '26510599933',
    projectId: 'cmsc23-c5l-ajhao',
    storageBucket: 'cmsc23-c5l-ajhao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn235eIxNk6h97OUnTZRKF2ImlxwR0xak',
    appId: '1:26510599933:ios:6eb34bea931956acad0094',
    messagingSenderId: '26510599933',
    projectId: 'cmsc23-c5l-ajhao',
    storageBucket: 'cmsc23-c5l-ajhao.appspot.com',
    iosClientId: '26510599933-1i7ocrcoub5gun3f6pbq7n6r83jk8pet.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn235eIxNk6h97OUnTZRKF2ImlxwR0xak',
    appId: '1:26510599933:ios:6eb34bea931956acad0094',
    messagingSenderId: '26510599933',
    projectId: 'cmsc23-c5l-ajhao',
    storageBucket: 'cmsc23-c5l-ajhao.appspot.com',
    iosClientId: '26510599933-1i7ocrcoub5gun3f6pbq7n6r83jk8pet.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
